name: Publish Docker Image
on:
  release:
    types: [published, edited]
permissions: 
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: skyloud/actions-publish-docker-ghcr@v5
      with:
        name: ${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_semver: true
        platforms: linux/amd64,linux/arm64
